### ISSUE TITLE
커스텀 에러 및 에러 핸들러 정의

### ISSUE THREAD

**Issue by yerim123456** [2024-TEAM-05/integrated-feed-backend#3]
## 📑 Description
프로젝트에서 exception 관리를 하기 위한 에러 관련 정의를 진행합니다.

## 📌 To Do
- [x] 커스텀 에러 정의
- [x] 에러 핸들러 정의

**Comment by jooda00** [comment]
💭 우측 Projects에 어제 의진님이 추가해주신 저희 project 연동해주셔도 좋을 것 같아요!
